### ISSUE TITLE
WebException when trying to connect to CardDAV server

### ISSUE THREAD

**Issue by Tywele** [Metric/CardDavNet#8]
When I'm trying to connect to a CardDAV server I get the following error message when catching the WebException.

`requestContentBody is neither an NSData or NSString object`

How do I fix this?

I get this error in the CardDavDemo. I put in the server address as URL and the username and password. When I'm using these credentials by accessing the server address directly in the browser everything works/I get a normal response from the server.

**Comment by Metric** [comment]
What OS are you trying to use this on? What CardDav server are you trying to connect to?

**Comment by Metric** [comment]
According to daylite CardDav for use with other applications should be:

Server: Your Server's Address
User Name: Your Daylite username
Password: Your Daylite password
Port: 6188

Are you properly setting port to 6188 in the server address?

**Comment by Tywele** [comment]
Sorry for not responding for so long. Yes I am setting the port to 6188.

**Comment by Metric** [comment]
Can't really test this myself to see what is going on. I do not have a Daylite account. Seems, like an issue on their end really, and not being compatible with the standard CardDav implementation. Either that, or they are using a newer specification of CardDav. Can any other non iOS / Swift / Objective C application connect to it, such as Outlook?

Because, the error you provided is an error they are giving back. Saying they did not detect a compatible NSString / NSData object, which are Objective C / Swift object types. My question is, what part is this failing at exactly in the library? The connection test part, or another part?

**Comment by Metric** [comment]
Closing never got a response, as to whether other window based services could connect to it.
